# Generated by Django 4.1.5 on 2023-01-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='사용자')),
                ('product_name', models.CharField(max_length=128, verbose_name='상품명')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('tstamp', models.DateTimeField(auto_now_add=True, verbose_name='댓글등록일시')),
            ],
        ),
    ]
